### ISSUE TITLE
Conflict between Firebase and mParticle causes crash

### ISSUE THREAD

**Issue by elefantel** [mParticle/mparticle-apple-sdk#118] opened 2020-11-07 10:24 UTC
We have both mParticle SDK and Firebase SDK in our app and we are getting a crashes at app launch. What we have noted is that whenever we have an mParticle crash, Firebase SDK is also present in one of the threads, accessing sqlite3. I believe this suggests an sqlite3 race condition.

We have reported the issue before in May [108](https://github.com/mParticle/mparticle-apple-sdk/issues/108) but wasn't resolved. It was recommended we disable swizzling - which we have, for all our SDKs.

We have also reported the issue to Firebase here [5503](https://github.com/firebase/firebase-ios-sdk/issues/5503) but they suggested it is likely to be an mParticle issue

`mParticle version: 7.16.0` (we have been getting this `_os_unfair_lock_unowned_abort` crash for over a year)
`Xcode version 12.1` (predates Xcode 12 - existed while we were on Xcode 11)

`mParticle crash thread`
```
Crashed: com.mparticle.messageQueue
0  libsystem_platform.dylib       0x19f46f04c _os_unfair_lock_unowned_abort + 36
1  libsystem_platform.dylib       0x19f4704f4 _os_unfair_lock_unlock_slow + 144
2  libsqlite3.dylib               0x19fc5ff18 sqlite3_snprintf + 3188
3  libsqlite3.dylib               0x19fc5fb18 sqlite3_snprintf + 2164
4  libsqlite3.dylib               0x19fcc2c0c sqlite3_free_table + 49564
5  libsqlite3.dylib               0x19fcc647c sqlite3_free_table + 64012
6  libsqlite3.dylib               0x19fcc5c30 sqlite3_free_table + 61888
7  libsqlite3.dylib               0x19fca0d00 sqlite3_step + 29564
8  libsqlite3.dylib               0x19fc99b40 sqlite3_step + 444
9  Luno                           0x101e0d0fc -[MPPersistenceController saveMessage:] + 1659 (MPPersistenceController.mm:1659)
10 Luno                           0x101da5ebc -[MPBackendController saveMessage:updateSession:] + 1777 (MPBackendController.mm:1777)
11 Luno                           0x101da3c30 -[MPBackendController logBaseEvent:completionHandler:] + 1520 (MPBackendController.mm:1520)
12 Luno                           0x101da3ed8 -[MPBackendController logEvent:completionHandler:] + 1541 (MPBackendController.mm:1541)
13 Luno                           0x101d8c8b0 __28-[MParticle logCustomEvent:]_block_invoke + 884 (mParticle.m:884)
14 libdispatch.dylib              0x19f2a0a38 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x19f2a17d4 _dispatch_client_callout + 16
16 libdispatch.dylib              0x19f24a324 _dispatch_lane_serial_drain$VARIANT$mp + 592
17 libdispatch.dylib              0x19f24ae40 _dispatch_lane_invoke$VARIANT$mp + 428
18 libdispatch.dylib              0x19f2534ac _dispatch_workloop_worker_thread + 596
19 libsystem_pthread.dylib        0x19f482114 _pthread_wqthread + 304
20 libsystem_pthread.dylib        0x19f484cd4 start_wqthread + 4
```

Firebase thread:
```
com.google.fira.worker
0  libsystem_kernel.dylib         0x19f3fe524 __guarded_open_np + 8
1  libsystem_kernel.dylib         0x19f3fdcec guarded_open_np + 44
2  libsqlite3.dylib               0x19fd0fe18 sqlite3_rekey + 4292
3  libsqlite3.dylib               0x19fc5f7e0 sqlite3_snprintf + 1340
4  libsqlite3.dylib               0x19fc5df88 sqlite3_vfs_find + 5548
5  libsqlite3.dylib               0x19fc5a844 sqlite3_open_v2 + 2656
6  Luno                           0x101e8def0 -[APMSqliteStore openAndValidateDatabase:] + 4326825712
7  Luno                           0x101e899fc -[APMSqliteStore initWithDatabasePath:error:] + 4326808060
8  Luno                           0x101e5f330 -[APMDatabase initializeDatabaseResourcesWithContext:databasePath:error:] + 4326634288
9  Luno                           0x101e55154 -[APMDatabase initWithDatabaseName:persistedConfig:error:] + 4326592852
10 Luno                           0x101e660f0 __47-[APMMeasurement startMeasurementOnWorkerQueue]_block_invoke + 4326662384
11 Luno                           0x101e65a18 -[APMMeasurement startMeasurementOnWorkerQueue] + 4326660632
12 Luno                           0x101e655a0 -[APMMeasurement setEnabledOnWorkerQueue:] + 4326659488
13 Luno                           0x101e65484 __29-[APMMeasurement setEnabled:]_block_invoke + 4326659204
14 Luno                           0x101e784b0 __51-[APMScheduler scheduleOnWorkerQueueBlockID:block:]_block_invoke + 4326737072
15 libdispatch.dylib              0x19f2a0a38 _dispatch_call_block_and_release + 24
16 libdispatch.dylib              0x19f2a17d4 _dispatch_client_callout + 16
17 libdispatch.dylib              0x19f24a324 _dispatch_lane_serial_drain$VARIANT$mp + 592
18 libdispatch.dylib              0x19f24ae40 _dispatch_lane_invoke$VARIANT$mp + 428
19 libdispatch.dylib              0x19f2534ac _dispatch_workloop_worker_thread + 596
20 libsystem_pthread.dylib        0x19f482114 _pthread_wqthread + 304
21 libsystem_pthread.dylib        0x19f484cd4 start_wqthread + 4
```

To get an idea about how bad this issue has been, see the Firebase crashlytics screenshot below (mParticle is by far the majority source of crashes).

We would really appreciate some help in getting this resolved.

![crashes](https://user-images.githubusercontent.com/17785504/99234760-9e3dee00-27fd-11eb-9f51-827873bd4775.png)

**Comment by samdozor** [comment] 2020-12-01 15:25
hey @elefantel noting here that I believe you've been working with mParticle technical support behind the scenes. Will keep this issue open as we investigate further.

**Comment by alexs-mparticle** [comment] 2021-03-29 14:28
Tracking internally as bug 58751

**Comment by alexs-mparticle** [comment] 2021-06-09 13:51
Hello all - unfortunately we [and Firebase] have be unable to find a root cause for this conflict. Without more information or reproducible steps we are blocked from move forward for now.

We will monitor the open Firebase issue: https://github.com/firebase/firebase-ios-sdk/issues/5503

**Comment by alexs-mparticle** [comment] 2021-12-03 17:07
Closing as there is no clear strategy to reproduce or resolve.

**Closed by alexs-mparticle** 2021-12-03 17:07 UTC
Labels: bug, blocked
