### ISSUE TITLE
Mixpanel Linker command failed with exit code 1(use -v to see invocation)

### ISSUE THREAD

**Issue by leozhao0709** [mParticle/mparticle-apple-sdk#45] opened 2017-06-23 04:18 UTC
Hi,

Not sure what happened tonight. It's even worked this afternoon, but since tonight, when I compiled, I always get this error. If I remove mparticle pod, then my project can build correctly. 
Any ideas?

**Comment by leozhao0709** [comment] 2017-06-23 06:08
I find if I contain the Mixpanel in my pod, then it will have this issue. So how do I fix it with mixpanel?

**Comment by leozhao0709** [comment] 2017-06-23 06:28
seems it will work for mixpanel 2.9.9, but mixpanel 3.1.7 will trigger this error.

**Comment by samdozor** [comment] 2017-06-23 13:41
hey @leozhao0709 - I believe this is a duplicate of https://github.com/mParticle/mparticle-apple-sdk/issues/44, closing for now.

**Closed by samdozor** 2017-06-23 13:41 UTC
